### PR TITLE
Added screenshots and their description in readme

### PR DESCRIPTION
**Pull request by dashaluna**

### CODE REVIEW

**Comment by dashaluna** [comment]
@johnbillion hmm, not sure why `md` is being generated with images being wrapped into `###`.

Also, there is tag added `[missing image]` - do I need to add anything in `txt` file? I thought it just picks up a file with name `screenshot-x.png` where `x` is the number in the list.

**Comment by johnbillion** [comment]
Ah, your screenshots need to be in the root directory, not inside `/assets`.

Not sure about the heading issue. Looks like it might be a "feature" of that script. I would manually remove the `###` markers.

**Comment by dashaluna** [comment]
NB: Reported on the repo: https://github.com/benbalter/WP-Readme-to-Github-Markdown/issues/17#issuecomment-144356307

**Comment by dashaluna** [comment]
@johnbillion review & merge

**Pull request merged**
