### PR TITLE
92: translations available to desc

### PR DESCRIPTION
**Pull request by dashaluna**
**NOTE**: needs PR #85 to be merged first

Issue: #92

### CODE REVIEW

**Comment by dashaluna** [comment]
@johnbillion review & merge

**Comment by johnbillion** [comment]
In my User Switching plugin, I [recently simplified the list of translations](https://github.com/johnbillion/user-switching/commit/7f4f0d254c037bb879f73c729aa829543211a9ec) so translators don't need to translate the names of available translations. Might want to do the same here.

**Comment by dashaluna** [comment]
@johnbillion I get 404

**Comment by dashaluna** [comment]
I thought it's nice to see the English version of the language name, no? :)

**Comment by johnbillion** [comment]
Yeah that's why I originally had the English names in there too, but it's not actually very useful to people looking for a translation in their language.

**Comment by dashaluna** [comment]
@johnbillion why not? I think it will be useful for me.. I might get confused what's what with the list growing :P

**Comment by dashaluna** [comment]
@johnbillion review & merge please :)

**Pull request merged**
